const dataChartHome = [
    { name: 'Jan', value: 400 },
    { name: 'Feb', value: 300 },
    { name: 'Mar', value: 200 },
    { name: 'Apr', value: 278 },
    { name: 'May', value: 189 },
    { name: 'Jun', value: 239 },
    { name: 'Jul', value: 349 },
    { name: 'Aug', value: 200 },
    { name: 'Sep', value: 300 },
    { name: 'Oct', value: 400 },
    { name: 'Nov', value: 100 },
    { name: 'Dec', value: 500 },
];

const users = [
    {
        id: 1,
        name: "John",
        lastName: "Doe",
        position: "Software Engineer",
        profile: "/images/profiles/1.png",
        email: "john.doe@gmail.com",
        phone: "+1 234 567 890",
        address: "1234 Elm Street, Springfield, USA"
    },
    {
        id: 2,
        name: "Jane",
        lastName: "Smith",
        position: "Product Manager",
        profile: "/images/profiles/5.jpg",
        email: "jane.smith@gmail.com",
        phone: "+1 234 567 891",
        address: "5678 Oak Avenue, Springfield, USA"
    },
    {
        id: 3,
        name: "Robert",
        lastName: "Brown",
        position: "Data Analyst",
        profile: "/images/profiles/2.jpg",
        email: "robert.brown@gmail.com",
        phone: "+1 234 567 892",
        address: "9101 Pine Road, Springfield, USA"
    },
    {
        id: 4,
        name: "Emily",
        lastName: "Clark",
        position: "UX Designer",
        profile: "/images/profiles/6.jpg",
        email: "emily.clark@gmail.com",
        phone: "+1 234 567 893",
        address: "1213 Cedar Blvd, Springfield, USA"
    },
    {
        id: 5,
        name: "Michael",
        lastName: "Johnson",
        position: "Backend Developer",
        profile: "/images/profiles/3.jpg",
        email: "michael.johnson@gmail.com",
        phone: "+1 234 567 894",
        address: "1415 Birch Lane, Springfield, USA"
    }
];

const TransActionsData = [
    { id: 0, img: '/images/profiles/1.png', customer: 'mobin', date: '12 Jun 2024', amount: 1_154_876, status: 'Approved' },
    { id: 1, img: '/images/profiles/2.jpg', customer: 'alireza', date: '15 Mar 2024', amount: 25_000_000, status: 'Declined' },
    { id: 2, img: '/images/profiles/3.jpg', customer: 'amir', date: '5 Feb 2024', amount: 5_000, status: 'pending' },
    { id: 3, img: '/images/profiles/4.jpg', customer: 'kian', date: '30 Jul 2024', amount: 11_000, status: 'Approved' },
]

const usersData = [
    { id: 0, img: '/images/profiles/1.png', customer: 'mobin', email: 'mobin@gmail.com', transaction: 1_154_876, status: 'active' },
    { id: 1, img: '/images/profiles/2.jpg', customer: 'alireza', email: 'alireza@gmail.com', transaction: 25_000_000, status: 'non-active' },
    { id: 2, img: '/images/profiles/3.jpg', customer: 'amir', email: 'amir@gmail.com', transaction: 5_000, status: 'active' },
    { id: 3, img: '/images/profiles/4.jpg', customer: 'kian', email: 'kian@gmail.com', transaction: 11_000, status: 'active' },
    { id: 4, img: '/images/profiles/5.jpg', customer: 'sara', email: 'sara@gmail.com', transaction: 521_000, status: 'non-active' },
    { id: 5, img: '/images/profiles/6.jpg', customer: 'mary', email: 'mary@gmail.com', transaction: 2_000, status: 'active' },
    { id: 6, img: '/images/profiles/1.png', customer: 'danial', email: 'danial@gmail.com', transaction: 10_000, status: 'non-active' },
    { id: 7, img: '/images/profiles/2.jpg', customer: 'reza', email: 'reza@gmail.com', transaction: 18_500, status: 'active' },
    { id: 8, img: '/images/profiles/3.jpg', customer: 'neda', email: 'neda@gmail.com', transaction: 70_000, status: 'active' },
    { id: 9, img: '/images/profiles/4.jpg', customer: 'shima', email: 'shima@gmail.com', transaction: 125_000, status: 'non-active' },
    { id: 10, img: '/images/profiles/5.jpg', customer: 'parsa', email: 'parsa@gmail.com', transaction: 900_000, status: 'active' },
    { id: 11, img: '/images/profiles/6.jpg', customer: 'mehdi', email: 'mehdi@gmail.com', transaction: 30_000, status: 'non-active' },
    { id: 12, img: '/images/profiles/1.png', customer: 'sina', email: 'sina@gmail.com', transaction: 45_000, status: 'active' },
    { id: 13, img: '/images/profiles/2.jpg', customer: 'fatemeh', email: 'fatemeh@gmail.com', transaction: 500_000, status: 'non-active' },
    { id: 14, img: '/images/profiles/3.jpg', customer: 'arash', email: 'arash@gmail.com', transaction: 250_000, status: 'active' },
    { id: 15, img: '/images/profiles/4.jpg', customer: 'zara', email: 'zara@gmail.com', transaction: 800_000, status: 'active' },
    { id: 16, img: '/images/profiles/5.jpg', customer: 'milad', email: 'milad@gmail.com', transaction: 100_000, status: 'non-active' },
    { id: 17, img: '/images/profiles/6.jpg', customer: 'sahar', email: 'sahar@gmail.com', transaction: 300_000, status: 'active' },
    { id: 18, img: '/images/profiles/1.png', customer: 'hassan', email: 'hassan@gmail.com', transaction: 10_000_000, status: 'active' },
    { id: 19, img: '/images/profiles/2.jpg', customer: 'mohammad', email: 'mohammad@gmail.com', transaction: 15_000_000, status: 'non-active' },
    { id: 20, img: '/images/profiles/3.jpg', customer: 'mahtab', email: 'mahtab@gmail.com', transaction: 7_000, status: 'active' },
    { id: 21, img: '/images/profiles/4.jpg', customer: 'farzad', email: 'farzad@gmail.com', transaction: 12_000, status: 'active' },
    { id: 22, img: '/images/profiles/5.jpg', customer: 'nima', email: 'nima@gmail.com', transaction: 500_000, status: 'non-active' },
    { id: 23, img: '/images/profiles/6.jpg', customer: 'armin', email: 'armin@gmail.com', transaction: 200_000, status: 'active' },
    { id: 24, img: '/images/profiles/1.png', customer: 'roya', email: 'roya@gmail.com', transaction: 1_000, status: 'non-active' },
    { id: 25, img: '/images/profiles/2.jpg', customer: 'bahar', email: 'bahar@gmail.com', transaction: 7_500, status: 'active' },
    { id: 26, img: '/images/profiles/3.jpg', customer: 'sam', email: 'sam@gmail.com', transaction: 11_500, status: 'active' },
    { id: 27, img: '/images/profiles/4.jpg', customer: 'amin', email: 'amin@gmail.com', transaction: 800_000, status: 'non-active' },
    { id: 28, img: '/images/profiles/5.jpg', customer: 'ramin', email: 'ramin@gmail.com', transaction: 1_500_000, status: 'active' },
    { id: 29, img: '/images/profiles/6.jpg', customer: 'mina', email: 'mina@gmail.com', transaction: 75_000, status: 'non-active' },
    { id: 30, img: '/images/profiles/1.png', customer: 'hossein', email: 'hossein@gmail.com', transaction: 12_000, status: 'active' },
    { id: 31, img: '/images/profiles/2.jpg', customer: 'ali', email: 'ali@gmail.com', transaction: 500_000, status: 'non-active' },
    { id: 32, img: '/images/profiles/3.jpg', customer: 'nazanin', email: 'nazanin@gmail.com', transaction: 900_000, status: 'active' },
    { id: 33, img: '/images/profiles/4.jpg', customer: 'haniyeh', email: 'haniyeh@gmail.com', transaction: 600_000, status: 'non-active' },
    { id: 34, img: '/images/profiles/5.jpg', customer: 'mohsen', email: 'mohsen@gmail.com', transaction: 50_000, status: 'active' },
    { id: 35, img: '/images/profiles/6.jpg', customer: 'rezaei', email: 'rezaei@gmail.com', transaction: 300_000, status: 'non-active' },
    { id: 36, img: '/images/profiles/1.png', customer: 'tina', email: 'tina@gmail.com', transaction: 40_000, status: 'active' },
    { id: 37, img: '/images/profiles/2.jpg', customer: 'mahdi', email: 'mahdi@gmail.com', transaction: 150_000, status: 'non-active' },
    { id: 38, img: '/images/profiles/3.jpg', customer: 'goli', email: 'goli@gmail.com', transaction: 20_000, status: 'active' },
    { id: 39, img: '/images/profiles/4.jpg', customer: 'arvin', email: 'arvin@gmail.com', transaction: 45_000, status: 'non-active' },
    { id: 40, img: '/images/profiles/5.jpg', customer: 'darya', email: 'darya@gmail.com', transaction: 800_000, status: 'active' },
    { id: 41, img: '/images/profiles/6.jpg', customer: 'omid', email: 'omid@gmail.com', transaction: 120_000, status: 'non-active' },
    { id: 42, img: '/images/profiles/1.png', customer: 'shirin', email: 'shirin@gmail.com', transaction: 10_500, status: 'active' },
    { id: 43, img: '/images/profiles/2.jpg', customer: 'kamran', email: 'kamran@gmail.com', transaction: 11_000, status: 'non-active' },
    { id: 44, img: '/images/profiles/3.jpg', customer: 'iman', email: 'iman@gmail.com', transaction: 80_000, status: 'active' },
    { id: 45, img: '/images/profiles/4.jpg', customer: 'arman', email: 'arman@gmail.com', transaction: 250_000, status: 'non-active' },
    { id: 46, img: '/images/profiles/5.jpg', customer: 'zahra', email: 'zahra@gmail.com', transaction: 450_000, status: 'active' },
    { id: 47, img: '/images/profiles/6.jpg', customer: 'pouya', email: 'pouya@gmail.com', transaction: 600_000, status: 'non-active' },
    { id: 48, img: '/images/profiles/1.png', customer: 'arash', email: 'arash2@gmail.com', transaction: 1_000_000, status: 'active' },
    { id: 49, img: '/images/profiles/2.jpg', customer: 'sadaf', email: 'sadaf@gmail.com', transaction: 500_000, status: 'non-active' },
];

export { dataChartHome, users, TransActionsData, usersData }